name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
    release:
        name: Publish Crate
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
                persist-credentials: false
                submodules: true

          - name: Install Rust Stable
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Publish Crate
            run: >
              cargo publish \
                --locked \
                --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
